### ISSUE TITLE
Onvalidatemerchant certificates 

### ISSUE THREAD

**Issue by nikl1425** [justeat/ApplePayJSSample#98]
Hi

First of all thanks for posting this project!

I have trouble understanding the usage of the certicates with the httpclient...

It seems like the apple servers refuses to establish a connection. When i look inside your controller you're creating a simple http post request attaching the body props as in the documentation.

However you are reading the data from the certicate instead of the merchant.id?

Also how and where do you attach the cert information (options) to the post-request, see attached picture below ?

![image](https://user-images.githubusercontent.com/36190689/130151867-28f4725f-3bdb-41df-882e-08a5a40b3ee2.png)

**Comment by martincostello** [comment]
As the merchant Id is contained within the certificate, it's read directly, rather than being configured manually in the configuration as well:

https://github.com/justeat/ApplePayJSSample/blob/66a6f5628282f38c195608a85629f2edd8e59959/src/ApplePayJS/Clients/MerchantCertificate.cs#L38-L63

The certificate is attached to the `HttpClient` as part of it being resolved by dependency injection when using [HttpClientFactory](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests):

https://github.com/justeat/ApplePayJSSample/blob/66a6f5628282f38c195608a85629f2edd8e59959/src/ApplePayJS/Startup.cs#L56-L74
